services:
  - type: web
    name: google-stststkkk-a-b-c-D-e-f-g-h-i-j-k-l-m-n-o-proxy-q-r-s-t-u-v-w-x-y-z10101080-cookie
    env: python
    region: Oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn --port $PORT --host 0.0.0.0 main:app"
